# Generated by Django 3.0.5 on 2020-04-29 23:50

import box.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chef', models.ForeignKey(on_delete=box.models.Recipe, to='box.Author')),
            ],
        ),
    ]
