# Generated by Django 3.0.5 on 2020-04-30 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_chef'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chef',
        ),
    ]
